/**
 * Defines the category or type of a recognized code pattern.
 * Used for filtering and cataloging mined code.
 */
export enum PatternType {
  FUNCTION = 'FUNCTION',
  CLASS = 'CLASS',
  HOOK = 'HOOK',
  UTILITY = 'UTILITY',
  COMPONENT = 'COMPONENT'
}

/**
 * Represents a node in the Abstract Syntax Tree (AST).
 * This is a recursive structure used for visualizing the code's topology.
 *
 * @property {string} name - The identifier or name of the AST node.
 * @property {string} type - The syntactic type of the node (e.g., 'FunctionDeclaration', 'VariableDeclarator').
 * @property {ASTNode[]} [children] - Optional child nodes representing the nested structure.
 * @property {string | number} [value] - Optional literal value associated with the node.
 */
export interface ASTNode {
  name: string;
  type: string;
  children?: ASTNode[];
  value?: string | number;
}

/**
 * Represents a summary of the AST topology.
 * Kept lightweight to fit within Firestore document limits.
 */
export interface ASTSummary {
  nodeCount: number;
  maxDepth: number;
}

/**
 * Represents a fully mined and analyzed code block with its metadata.
 * It contains the source code, analysis scores, and its AST structure metadata.
 *
 * @property {string} id - A unique identifier for the mined pattern.
 * @property {string} name - A descriptive name for the pattern.
 * @property {PatternType} type - The structural category of the pattern.
 * @property {string} description - A brief summary of what the pattern does.
 * @property {string} code - The raw source code of the pattern.
 * @property {number} complexity - A cyclomatic complexity score (typically 1-10).
 * @property {string[]} tags - Semantic tags associated with the pattern for searching.
 * @property {string} astStorageUri - Pointer to the full AST JSON blob in the Phantom Dimension (Storage).
 * @property {ASTSummary} astSummary - Lightweight topological summary of the AST.
 * @property {number} confidence - The AI's confidence score in the pattern's validity (0-1).
 * @property {string} sovereignRating - A classification indicating stability (e.g., 'STABLE', 'VOLATILE', 'CRITICAL').
 * @property {string} usageDocs - Documentation explaining how to use the pattern.
 * @property {'USER_INPUT' | 'NEURAL_MINE'} origin - Indicates if the pattern was manually extracted from user input or generated by the scout engine.
 * @property {GoldenScar} [goldenScar] - The optional Golden Scar Protocol injection.
 */

/**
 * Represents the Paraconsistent Human Adjudication (Golden Scar Protocol).
 * Used to inject "Paraconsistent Tension" where humans adjudicate AI's output.
 *
 * @property {string} adjudicator - The identifier of the human operator.
 * @property {string} rationale - The contextual justification for the adjudication.
 * @property {number} tensionWeight - The weight representing the human empirical governance (e.g., 1.618).
 * @property {string} timestamp - The ISO string timestamp of the adjudication.
 */
export interface GoldenScar {
  adjudicator: string;
  rationale: string;
  tensionWeight: number;
  timestamp: string;
}


/**
 * Holds a proposed AI refactor in a state of Paraconsistent Tension.
 * It must be explicitly resolved by a human operator using the Golden Scar Protocol.
 */
export interface EpistemicEscrow {
  proposedCode: string;
  proposedComplexity: number;
  tensionMetric: number; // e.g., CFDI (Confidence-Fidelity Divergence Index)
  status: 'PENDING' | 'RESOLVED_ACCEPTED' | 'RESOLVED_REJECTED';
}

export interface CodePattern {
  id: string;
  name: string;
  type: PatternType;
  description: string;
  code: string;
  complexity: number; // 1-10
  tags: string[];
  astStorageUri: string;
  astSummary: ASTSummary;
  confidence: number;
  sovereignRating: string; // "STABLE", "VOLATILE", "CRITICAL"
  usageDocs: string;
  origin: 'USER_INPUT' | 'NEURAL_MINE';
  goldenScar?: GoldenScar;
  epistemicEscrow?: EpistemicEscrow;
}

/**
 * Tracks the state and progress of an ongoing mining operation.
 *
 * @property {string} id - A unique identifier for the mining session.
 * @property {'IDLE' | 'SCANNING' | 'ANALYZING' | 'COMPLETED' | 'FAILED'} status - The current operational state of the session.
 * @property {number} progress - A percentage (0-100) representing completion progress.
 * @property {string[]} logs - A chronological list of operational logs and events.
 * @property {number} patternsFound - The total number of reusable code patterns successfully identified so far.
 */
export interface MiningSession {
  id: string;
  status: 'IDLE' | 'SCANNING' | 'ANALYZING' | 'COMPLETED' | 'FAILED';
  progress: number;
  logs: string[];
  patternsFound: number;
}
